import path from 'node:path';

import type { ProviderWriteOptions, ProviderWriteResult } from '../../types';
import { ExpoModulesCoreCmakeTarget } from '../../config/constants';
import { HarmonyAutolinkingError } from '../../errors';
import { normalizeBuildType } from '../../config/options';
import { selectActiveProviders, resolveProviderSources } from './source';
import { publishArtifactsAsync } from '../transaction/publish';
import { emitLog, sortedUniqueStrings } from '../../utilities/values';
import { assertVerificationSucceeded, verifyModulesAsync } from '../../autolinking/verify';
import { providerAlias } from './names';
import { renderArkTsHostProviderSource } from './host';

function quoteCppString(value) {
  return JSON.stringify(value);
}

function collectProviders(descriptors, buildType = 'debug') {
  const providers = [];

  for (const descriptor of descriptors) {
    for (const provider of selectActiveProviders(descriptor, buildType)) {
      providers.push({ ...provider, packageName: descriptor.packageName });
    }
  }

  return providers.sort((left, right) => left.identifier.localeCompare(right.identifier, 'en')
    || left.className.localeCompare(right.className, 'en'));
}

function renderCppProviderSource(descriptors, buildType = 'debug') {
  const providers = collectProviders(descriptors, buildType);
  const headers = sortedUniqueStrings(providers.map(provider => provider.header));
  const lines = [
    '// @generated by @expo-harmony/expo-modules-autolinking. Do not edit.',
    '#include <ExpoModulesCore.h>',
  ];

  for (const header of headers) lines.push(`#include <${header}>`);
  lines.push('', 'namespace {');

  for (const provider of providers) {
    const alias = providerAlias(provider);
    lines.push(`using ${alias} = ${provider.className};`);
    lines.push(`EXPO_HARMONY_REGISTER_PROVIDER(${alias}, ${quoteCppString(provider.identifier)});`);
  }

  lines.push('} // namespace', '');
  return lines.join('\n');
}

function renderCmakeFile(descriptors, buildType = 'debug') {
  const providers = collectProviders(descriptors, buildType);
  const targets = sortedUniqueStrings(providers.map(provider => provider.cmakeTargetName));
  const sources = resolveProviderSources(descriptors, buildType).map(source => ({
    ...source,
    targets: sortedUniqueStrings(
      selectActiveProviders(source.descriptor, buildType).map(provider => provider.cmakeTargetName)
    ),
  }));

  const lines = [
    '# @generated by @expo-harmony/expo-modules-autolinking. Do not edit.',
    'set(_EXPO_HARMONY_AUTOLINKING_DIR "${CMAKE_CURRENT_LIST_DIR}")',
    'function(expo_harmony_autolink_modules target)',
    '  if(NOT TARGET "${target}")',
    '    message(FATAL_ERROR "Expo Harmony autolinking target does not exist: ${target}")',
    '  endif()',
  ];

  sources.forEach((source, index) => {
    if (source.rnohManaged) {
      for (const target of source.targets) {
        lines.push(`  if(NOT TARGET ${target})`);
        lines.push(`    message(FATAL_ERROR "RNOH did not define Provider target ${target} from ${source.ohPackageName}")`);
        lines.push('  endif()');
      }
      return;
    }
    lines.push('  if(NOT DEFINED OH_MODULES_DIR)');
    lines.push('    message(FATAL_ERROR "OH_MODULES_DIR is required to load Expo Harmony Provider HARs")');
    lines.push('  endif()');
    for (const target of source.targets) {
      lines.push(`  if(TARGET ${target})`);
      lines.push(`    message(FATAL_ERROR "Provider target ${target} already exists before loading ${source.ohPackageName}")`);
      lines.push('  endif()');
    }
    lines.push(
      `  add_subdirectory("\${OH_MODULES_DIR}/${source.ohPackageName}/src/main/cpp" `
      + `"\${CMAKE_CURRENT_BINARY_DIR}/expo-harmony-provider-${index}")`
    );
    for (const target of source.targets) {
      lines.push(`  if(NOT TARGET ${target})`);
      lines.push(`    message(FATAL_ERROR "Provider HAR ${source.ohPackageName} did not define target ${target}")`);
      lines.push('  endif()');
    }
  });
  lines.push(
    '  target_sources("${target}" PRIVATE',
    '    "${_EXPO_HARMONY_AUTOLINKING_DIR}/ExpoModulesAutolinkingProvider.cpp"',
    '  )',
    '  target_link_libraries("${target}" PRIVATE',
    `    ${ExpoModulesCoreCmakeTarget}`
  );

  for (const target of targets) lines.push(`    ${target}`);
  lines.push('  )', 'endfunction()', '');
  return lines.join('\n');
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function createProviderArtifactsAsync(options: Record<string, any> = {}) {
  const buildType = normalizeBuildType(options.buildType);
  let verified = options.verifiedDescriptors;

  if (!Array.isArray(verified)) {
    const verification = await verifyModulesAsync(options.modules !== undefined
      ? { modules: options.modules }
      : options);
    assertVerificationSucceeded(verification, 'provider-generation');
    verified = verification.modules;
  }

  const filter = options.packages === undefined ? null : new Set(options.packages);
  const descriptors = filter === null
    ? verified
    : verified.filter(descriptor => filter.has(descriptor.packageName));
  const providers = collectProviders(descriptors, buildType);

  return {
    buildType,
    modules: descriptors,
    providerCount: providers.length,
    source: renderCppProviderSource(descriptors, buildType),
    cmake: renderCmakeFile(descriptors, buildType),
    hostSource: renderArkTsHostProviderSource(descriptors),
  };
}

async function writeProviderArtifactsAsync(options: ProviderWriteOptions): Promise<ProviderWriteResult> {
  if (typeof options.target !== 'string' || !options.target) {
    throw new HarmonyAutolinkingError('INVALID_OPTIONS', 'generate-modules-provider requires a non-empty target path.', { stage: 'generate-modules-provider' });
  }

  const target = path.resolve(options.target);
  const artifacts = await createProviderArtifactsAsync(options);
  const sourcePath = path.join(target, 'ExpoModulesAutolinkingProvider.cpp');
  const cmakePath = path.join(target, 'expo-modules-autolinking.cmake');
  await publishArtifactsAsync({
    lockPath: path.join(target, '.expo-modules-autolinking.lock'),
    files: [
      { target: sourcePath, content: artifacts.source },
      { target: cmakePath, content: artifacts.cmake },
    ],
    allowedRoot: target,
  });

  const result = {
    sourcePath,
    cmakePath,
    providerCount: artifacts.providerCount,
    buildType: artifacts.buildType,
  };

  emitLog(options.logger, 'info', 'Harmony Provider artifacts were generated.', {
    providerCount: result.providerCount,
    buildType: result.buildType,
  });
  return result;
}

export {
  collectProviders,
  writeProviderArtifactsAsync,
  createProviderArtifactsAsync,
  renderCmakeFile,
  renderCppProviderSource,
};
