import { HarmonyAutolinkingError } from '../../errors';
import { HostMetadataFields } from '../../metadata/host';

function collectHostExtensions(descriptors) {
  const collected = Object.fromEntries(HostMetadataFields.map(field => [field, []]));

  for (const descriptor of [...descriptors].sort((left, right) => (
    left.packageName.localeCompare(right.packageName, 'en')
  ))) {
    const declarations = HostMetadataFields.flatMap(field => descriptor.expo[field] || []);
    if (declarations.length === 0) continue;

    const name = descriptor.arkTs?.ohPackageName;
    if (!name) {
      throw new HarmonyAutolinkingError(
        'INVALID_METADATA',
        'Harmony host extension classes must be exported by the module primary HAR.',
        { packageName: descriptor.packageName, stage: 'generate-host-provider' }
      );
    }

    for (const field of HostMetadataFields) {
      for (const className of descriptor.expo[field] || []) {
        collected[field].push({ className, ohPackageName: name, packageName: descriptor.packageName });
      }
    }
  }

  return collected;
}

function moduleRegistrationId(ohPackageName, moduleClass) {
  return `${ohPackageName}:${moduleClass}`;
}

function collectArkTsModuleRegistrations(descriptors) {
  const registrations = [];

  for (const descriptor of [...descriptors].sort((left, right) => (
    left.packageName.localeCompare(right.packageName, 'en')
  ))) {
    if (descriptor.harmony.modules.length === 0) continue;
    const arkTs = descriptor.arkTs;
    if (!arkTs) {
      throw new HarmonyAutolinkingError(
        'INVALID_METADATA',
        'Harmony ArkTS modules require the conventional Harmony library package.',
        { packageName: descriptor.packageName, stage: 'generate-host-provider' }
      );
    }
    for (const moduleClass of descriptor.harmony.modules) {
      registrations.push({
        moduleClass,
        ohPackageName: arkTs.ohPackageName,
        packageName: descriptor.packageName,
        registrationId: moduleRegistrationId(arkTs.ohPackageName, moduleClass),
      });
    }
  }
  return registrations;
}

function renderArkTsHostProviderSource(descriptors) {
  const extensions = collectHostExtensions(descriptors);
  const registrations = collectArkTsModuleRegistrations(descriptors);
  const imports = new Map();

  for (const field of HostMetadataFields) {
    for (const extension of extensions[field]) {
      const key = `${extension.ohPackageName}\0${extension.className}`;
      if (!imports.has(key)) {
        imports.set(key, {
          ...extension,
          alias: `ExpoHarmonyHostExtension${imports.size}`,
        });
      }
      extension.alias = imports.get(key).alias;
    }
  }

  const lines = [
    '/**',
    ' * Automatically generated by @expo-harmony/expo-modules-autolinking.',
    ' */',
    '',
  ];

  lines.push(
    `import { ExpoHarmonyHostState } from '@expo-harmony/expo-modules-core/Autolinking';`,
    'import type {',
    '  ExpoHarmonyHostProvider,',
    ...(registrations.length > 0 ? ['  ExpoModuleContext,'] : []),
    '  ExpoModuleRegistration,',
    `} from '@expo-harmony/expo-modules-core/Autolinking';`
  );

  registrations.forEach((registration, index) => {
    registration.alias = `ExpoHarmonyModule${index}`;
    lines.push(
      `import { ${registration.moduleClass} as ${registration.alias} } from '${registration.ohPackageName}';`
    );
  });

  for (const extension of imports.values()) {
    lines.push(
      `import { ${extension.className} as ${extension.alias} } from '${extension.ohPackageName}';`
    );
  }

  lines.push(
    '',
    'class GeneratedExpoHarmonyHostProvider implements ExpoHarmonyHostProvider {',
    '  readonly hostState: ExpoHarmonyHostState = new ExpoHarmonyHostState();',
    '',
    '  readonly expoModules: ExpoModuleRegistration[] = ['
  );
  for (const registration of registrations) {
    lines.push(
      '    {',
      `      registrationId: ${JSON.stringify(registration.registrationId)},`,
      `      moduleClassName: ${JSON.stringify(registration.moduleClass)},`,
      `      factory: (context: ExpoModuleContext) => new ${registration.alias}(context),`,
      '    },'
    );
  }
  lines.push(
    '  ];',
    '}',
    '',
    'export const expoHarmonyHostProvider: ExpoHarmonyHostProvider =',
    '  new GeneratedExpoHarmonyHostProvider();',
    '',
    '@Builder',
    'export function ExpoHarmonyRootView(): void {'
  );

  for (const extension of extensions.rootViewComponents) {
    lines.push(`  ${extension.alias}()`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

export {
  moduleRegistrationId,
  renderArkTsHostProviderSource,
};
