import { HarmonyAutolinkingError } from '../../errors';
import { HostMetadataFields } from '../../metadata/host';
import { resolveRnohMetadata } from '../rnoh/packageMetadata';

function collectHostExtensions(descriptors) {
  const collected = Object.fromEntries(HostMetadataFields.map(field => [field, []]));

  for (const descriptor of [...descriptors].sort((left, right) => (
    left.packageName.localeCompare(right.packageName, 'en')
  ))) {
    const declarations = HostMetadataFields.flatMap(field => descriptor.expo[field] || []);
    if (declarations.length === 0) continue;

    const name = resolveRnohMetadata(descriptor).harMappings[0]?.ohPackageName;
    if (!name) {
      throw new HarmonyAutolinkingError(
        'INVALID_METADATA',
        'Harmony host extension classes must be exported by the module primary HAR.',
        { packageName: descriptor.packageName, stage: 'generate-host-provider' }
      );
    }

    for (const field of HostMetadataFields) {
      for (const className of descriptor.expo[field] || []) {
        collected[field].push({ className, ohPackageName: name, packageName: descriptor.packageName });
      }
    }
  }

  return collected;
}

function renderArkTsHostProviderSource(descriptors) {
  const extensions = collectHostExtensions(descriptors);
  const imports = new Map();

  for (const field of HostMetadataFields) {
    for (const extension of extensions[field]) {
      const key = `${extension.ohPackageName}\0${extension.className}`;
      if (!imports.has(key)) {
        imports.set(key, {
          ...extension,
          alias: `ExpoHarmonyHostExtension${imports.size}`,
        });
      }
      extension.alias = imports.get(key).alias;
    }
  }

  const lines = [
    '/**',
    ' * Automatically generated by @expo-harmony/expo-modules-autolinking.',
    ' */',
    '',
    'import type {',
    '  ExpoAbilityLifecycleSubscriber,',
    '  ExpoHarmonyHostProvider,',
    '  ExpoReactInstanceLifecycleListener,',
    `} from '@expo-harmony/expo-modules-core';`,
  ];

  for (const extension of imports.values()) {
    lines.push(
      `import { ${extension.className} as ${extension.alias} } from '${extension.ohPackageName}';`
    );
  }

  lines.push(
    '',
    'class GeneratedExpoHarmonyHostProvider implements ExpoHarmonyHostProvider {',
    '  readonly abilityLifecycleSubscribers: ExpoAbilityLifecycleSubscriber[] = ['
  );
  for (const extension of extensions.abilityLifecycleSubscribers) {
    lines.push(`    new ${extension.alias}(),`);
  }
  lines.push(
    '  ];',
    '',
    '  readonly reactInstanceLifecycleListeners: ExpoReactInstanceLifecycleListener[] = ['
  );
  for (const extension of extensions.reactInstanceLifecycleListeners) {
    lines.push(`    new ${extension.alias}(),`);
  }
  lines.push(
    '  ];',
    '}',
    '',
    'export const expoHarmonyHostProvider: ExpoHarmonyHostProvider =',
    '  new GeneratedExpoHarmonyHostProvider();',
    '',
    '@Builder',
    'export function ExpoHarmonyRootView(): void {'
  );

  for (const extension of extensions.rootViewComponents) {
    lines.push(`  ${extension.alias}()`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

export {
  collectHostExtensions,
  renderArkTsHostProviderSource,
};
