'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { createRunOncePlugin } = require('@expo/config-plugins');
const {
  recordManagedFile,
  registerHarmonyConfigPlugin,
  withHarmonyDangerousMod,
  withModuleJson,
} = require('@expo-harmony/config-plugins');

const pkg = require('../package.json');

// Keep these values aligned with ExpoBackgroundTaskPackage.ets.
const EXTENSION_NAME = 'ExpoBackgroundTaskWorkScheduler';
const EXTENSION_SOURCE = './ets/expo-background-task/ExpoBackgroundTaskWorkScheduler.ets';
const GENERATED_MARKER = 'Automatically generated by @expo-harmony/expo-background-task.';
const GENERATED_SOURCE = `/**
 * ${GENERATED_MARKER}
 */

import {
  ExpoBackgroundTaskWorkSchedulerExtension as ExpoBackgroundTaskWorkSchedulerExtensionBase,
} from '@expo-harmony/expo-background-task';

export default class ExpoBackgroundTaskWorkScheduler
  extends ExpoBackgroundTaskWorkSchedulerExtensionBase {}
`;

function updateModuleJson(json) {
  const module = json.module && typeof json.module === 'object' && !Array.isArray(json.module)
    ? json.module
    : {};
  const extensions = Array.isArray(module.extensionAbilities)
    ? module.extensionAbilities
    : [];
  const matches = extensions.filter(extension => extension?.name === EXTENSION_NAME);

  if (matches.length > 1) {
    throw new TypeError(`Harmony module declares ${EXTENSION_NAME} more than once.`);
  }
  if (matches.length === 1) {
    const current = matches[0];
    if (current.type !== 'workScheduler'
      || current.srcEntry !== EXTENSION_SOURCE
      || current.exported !== false) {
      throw new TypeError(`Harmony module already declares ${EXTENSION_NAME} with incompatible settings.`);
    }

    return json;
  }

  return {
    ...json,
    module: {
      ...module,
      extensionAbilities: [
        ...extensions,
        {
          name: EXTENSION_NAME,
          srcEntry: EXTENSION_SOURCE,
          type: 'workScheduler',
          exported: false,
        },
      ],
    },
  };
}

function withHarmonyBackgroundTask(config) {
  const enabled = config.harmony?.bundleName || config.platforms?.includes('harmony');
  if (!enabled) return config;

  config = registerHarmonyConfigPlugin(config, pkg.name);
  config = withModuleJson(config, (mod) => {
    mod.modResults = updateModuleJson(mod.modResults);
    return mod;
  });

  return withHarmonyDangerousMod(config, async (mod) => {
    const file = path.join(
      mod.modRequest.platformProjectRoot,
      'entry/src/main/ets/expo-background-task/ExpoBackgroundTaskWorkScheduler.ets'
    );

    await writeGeneratedSource(file);

    recordManagedFile(mod, file, pkg.name);

    return mod;
  });
}

async function writeGeneratedSource(file) {
  let current;

  try {
    current = await fs.promises.readFile(file, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw new Error(`Unable to inspect Harmony source '${file}': ${String(error)}`);
    }
  }

  if (
    current !== undefined
    && current !== GENERATED_SOURCE
    && !current.includes(GENERATED_MARKER)
  ) {
    throw new TypeError(
      `Harmony source '${file}' already exists and is not managed by ${pkg.name}.`
    );
  }

  await fs.promises.mkdir(path.dirname(file), { recursive: true });
  await fs.promises.writeFile(file, GENERATED_SOURCE);
}

module.exports = createRunOncePlugin(withHarmonyBackgroundTask, pkg.name, pkg.version);
module.exports.EXTENSION_NAME = EXTENSION_NAME;
module.exports.EXTENSION_SOURCE = EXTENSION_SOURCE;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
module.exports.GENERATED_SOURCE = GENERATED_SOURCE;
module.exports.updateModuleJson = updateModuleJson;
module.exports.withHarmonyBackgroundTask = withHarmonyBackgroundTask;
module.exports.writeGeneratedSource = writeGeneratedSource;
