import fs from 'node:fs';
import path from 'node:path';

import { resolveTemplateFile } from './dependencies';

async function readTextIfExistsAsync(file: string): Promise<string | null> {
  try {
    return await fs.promises.readFile(file, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    return Promise.reject(error);
  }
}

async function writeFileAtomicAsync(file: string, content: string) {
  await fs.promises.mkdir(path.dirname(file), { recursive: true });
  const temporary = path.join(path.dirname(file), `.${path.basename(file)}.${process.pid}.tmp`);
  try {
    await fs.promises.writeFile(temporary, content);
    await fs.promises.rename(temporary, file);
  } finally {
    await fs.promises.rm(temporary, { force: true }).catch(() => {});
  }
}

async function writeFileIfChangedAsync(file: string, content: string) {
  const existing = await readTextIfExistsAsync(file);
  if (existing !== content) await writeFileAtomicAsync(file, content);
}

async function ensureGitignoreEntryAsync(file: string, entry: string) {
  const content = await readTextIfExistsAsync(file) ?? '';
  const normalized = content.replace(/\r\n?/g, '\n');
  if (normalized.split('\n').includes(entry)) return;

  const next = `${normalized.replace(/\n*$/, '')}${normalized.trim() ? '\n' : ''}${entry}\n`;
  await writeFileAtomicAsync(file, next);
}

async function writeExpoCmakeWrapperAsync(harmonyProjectPath: string) {
  const file = path.join(harmonyProjectPath, 'entry/src/main/cpp/generated/CMakeLists.txt');
  const content = await fs.promises.readFile(resolveTemplateFile('harmony/entry/src/main/cpp/generated/CMakeLists.txt'), 'utf8');
  await writeFileIfChangedAsync(file, content);
  return file;
}

function sanitizeExpoConfig(config) {
  const value = { ...config };
  delete value._internal;
  delete value.mods;
  delete value.hooks;
  if (value.ios?.config) {
    value.ios = { ...value.ios };
    delete value.ios.config;
  }
  if (value.android?.config) {
    value.android = { ...value.android };
    delete value.android.config;
  }
  if (value.updates?.codeSigningCertificate || value.updates?.codeSigningMetadata) {
    value.updates = { ...value.updates };
    delete value.updates.codeSigningCertificate;
    delete value.updates.codeSigningMetadata;
  }
  if (value.harmony?.signingConfigFile) {
    value.harmony = { ...value.harmony };
    delete value.harmony.signingConfigFile;
  }
  return JSON.parse(JSON.stringify(value));
}

async function writeExpoConstantsHeaderAsync(projectRoot, normalized, expoConfig) {
  const file = path.join(projectRoot, 'harmony/entry/src/main/cpp/generated/ExpoHarmonyGeneratedConstants.h');
  const appConfig = sanitizeExpoConfig(expoConfig);
  appConfig.version ??= normalized.versionName;
  appConfig.harmony = {
    ...(appConfig.harmony || {}),
    bundleName: normalized.bundleName,
    versionCode: normalized.versionCode,
    versionName: normalized.versionName,
    targetApiVersion: normalized.targetApiVersion,
  };
  const content = `#pragma once

// Deterministically generated by @expo-harmony/prebuild-config.
#define EXPO_HARMONY_APP_CONFIG_JSON ${JSON.stringify(JSON.stringify(appConfig))}
#define EXPO_HARMONY_BUNDLE_NAME ${JSON.stringify(normalized.bundleName)}
#define EXPO_HARMONY_VERSION_NAME ${JSON.stringify(normalized.versionName)}
#define EXPO_HARMONY_VERSION_CODE ${normalized.versionCode}
#ifdef NDEBUG
#define EXPO_HARMONY_DEBUG_MODE false
#else
#define EXPO_HARMONY_DEBUG_MODE true
#endif
`;

  await writeFileIfChangedAsync(file, content);
  return file;
}

export {
  ensureGitignoreEntryAsync,
  writeExpoCmakeWrapperAsync,
  writeExpoConstantsHeaderAsync,
};
