import { isRnohAutolinkingDisabled } from './native';
import type { HarmonyBuildDescriptor } from './buildDescriptor';
import { TEMPLATE_PLACEHOLDERS } from './template';

function normalizeSource(source, label) {
  if (typeof source !== 'string' || !source.trim()) {
    throw new TypeError(`${label} must start from the canonical Harmony template source.`);
  }
  return source.replace(/\r\n?/gu, '\n');
}

function replacePlaceholder(source, placeholder, value, label) {
  const count = source.split(placeholder).length - 1;

  if (count !== 1) {
    throw new TypeError(
      `Canonical Harmony template has ${count} ${label} placeholders; expected exactly one.`
    );
  }

  return source.replace(placeholder, () => value);
}

function quoteSingle(value) {
  return `'${String(value)
    .replace(/\\/gu, '\\\\')
    .replace(/'/gu, `\\'`)
    .replace(/\r/gu, '\\r')
    .replace(/\n/gu, '\\n')}'`;
}

function renderReactNativeConfig() {
  return `// Generated by @expo-harmony/prebuild-config. Customize through withReactNativeConfig.
// React Native CLI loads this generated JavaScript file through CommonJS.
module.exports = require('@react-native-oh/react-native-harmony-cli/react-native.config.js');
`;
}

function renderRootHvigor(source, build: HarmonyBuildDescriptor) {
  source = normalizeSource(source, build.projectFiles.rootHvigor);

  return replacePlaceholder(
    source,
    quoteSingle(TEMPLATE_PLACEHOLDERS.bundlePath),
    quoteSingle(build.export.bundle),
    'embedded bundle path'
  );
}

function renderEntryAbility(source, harmony) {
  source = normalizeSource(source, 'EntryAbility.ets');

  return replacePlaceholder(
    source,
    TEMPLATE_PLACEHOLDERS.abilityName,
    harmony.abilityName,
    'ability class'
  );
}

function renderIndexPage(source, harmony) {
  source = normalizeSource(source, 'Index.ets');

  return replacePlaceholder(
    source,
    JSON.stringify(TEMPLATE_PLACEHOLDERS.appLabel),
    JSON.stringify(harmony.label),
    'RN instance name'
  );
}

function renderCanonical(source, label) {
  return normalizeSource(source, label);
}

const renderArktsPackageProvider = source => renderCanonical(source, 'PackageProvider.ets');
const renderCmakeLists = source => renderCanonical(source, 'CMakeLists.txt');
const renderCppPackageProvider = source => renderCanonical(source, 'PackageProvider.cpp');

export {
  isRnohAutolinkingDisabled,
  renderArktsPackageProvider,
  renderCanonical,
  renderCmakeLists,
  renderCppPackageProvider,
  renderEntryAbility,
  renderIndexPage,
  renderReactNativeConfig,
  renderRootHvigor,
};
