'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { createRunOncePlugin } = require('@expo/config-plugins');
const {
  HarmonyConfigPluginError,
  normalizeHarmonyConfig,
  recordManagedFile,
  registerHarmonyConfigPlugin,
  withHarmonyDangerousMod,
} = require('@expo-harmony/config-plugins');

const pkg = require('../package.json');

class ExpoConstantsPluginError extends HarmonyConfigPluginError {
  constructor(code, message, options = {}) {
    super(code, message, { ...options, operation: 'generate-constants' });
    this.name = 'ExpoConstantsPluginError';
  }
}

function sanitizeExpoConfig(config) {
  const value = { ...config };

  delete value._internal;
  delete value.mods;
  delete value.hooks;
  if (value.ios?.config) {
    value.ios = { ...value.ios };
    delete value.ios.config;
  }
  if (value.android?.config) {
    value.android = { ...value.android };
    delete value.android.config;
  }
  if (value.updates?.codeSigningCertificate || value.updates?.codeSigningMetadata) {
    value.updates = { ...value.updates };
    delete value.updates.codeSigningCertificate;
    delete value.updates.codeSigningMetadata;
  }
  if (value.harmony?.signingConfigFile) {
    value.harmony = { ...value.harmony };
    delete value.harmony.signingConfigFile;
  }

  return JSON.parse(JSON.stringify(value));
}

async function readTextIfExistsAsync(file) {
  try {
    return await fs.promises.readFile(file, 'utf8');
  } catch (cause) {
    if (cause.code === 'ENOENT') return null;

    throw new ExpoConstantsPluginError(
      'ERR_HARMONY_CONSTANTS_READ_FAILED',
      `Unable to read the generated Expo Constants header: ${file}`,
      { cause, file }
    );
  }
}

async function writeFileAtomicAsync(file, content) {
  const directory = path.dirname(file);
  const temp = path.join(directory, `.${path.basename(file)}.${process.pid}.tmp`);

  await fs.promises.mkdir(directory, { recursive: true });

  try {
    await fs.promises.writeFile(temp, content);
    await fs.promises.rename(temp, file);
  } finally {
    await fs.promises.rm(temp, { force: true }).catch(() => {});
  }
}

async function writeFileIfChangedAsync(file, content) {
  const current = await readTextIfExistsAsync(file);
  if (current !== content) await writeFileAtomicAsync(file, content);
}

async function writeExpoConstantsHeaderAsync(root, harmony, config) {
  const file = path.join(root, 'entry/src/main/cpp/generated/ExpoHarmonyGeneratedConstants.h');

  const app = sanitizeExpoConfig(config);
  app.version ??= harmony.versionName;
  app.harmony = {
    ...(app.harmony || {}),
    bundleName: harmony.bundleName,
    versionCode: harmony.versionCode,
    versionName: harmony.versionName,
    targetApiVersion: harmony.targetApiVersion,
  };

  const content = `#pragma once

// Deterministically generated by @expo-harmony/expo-constants.
#define EXPO_HARMONY_APP_CONFIG_JSON ${JSON.stringify(JSON.stringify(app))}
#define EXPO_HARMONY_BUNDLE_NAME ${JSON.stringify(harmony.bundleName)}
#define EXPO_HARMONY_VERSION_NAME ${JSON.stringify(harmony.versionName)}
#define EXPO_HARMONY_VERSION_CODE ${harmony.versionCode}
#ifdef NDEBUG
#define EXPO_HARMONY_DEBUG_MODE false
#else
#define EXPO_HARMONY_DEBUG_MODE true
#endif
`;

  await writeFileIfChangedAsync(file, content);

  return file;
}

function withHarmonyConstants(config) {
  const enabled = config.harmony?.bundleName || config.platforms?.includes('harmony');
  if (!enabled) return config;

  config = registerHarmonyConfigPlugin(config, pkg.name);

  return withHarmonyDangerousMod(config, async (mod) => {
    const harmony = normalizeHarmonyConfig(mod.modRawConfig);

    const file = await writeExpoConstantsHeaderAsync(mod.modRequest.platformProjectRoot, harmony, mod.modRawConfig);

    recordManagedFile(mod, file, pkg.name);

    return mod;
  });
}

module.exports = createRunOncePlugin(withHarmonyConstants, pkg.name, pkg.version);
module.exports.sanitizeExpoConfig = sanitizeExpoConfig;
module.exports.withHarmonyConstants = withHarmonyConstants;
module.exports.writeExpoConstantsHeaderAsync = writeExpoConstantsHeaderAsync;
