import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import JSON5 from 'json5';

const StampPath = '.hvigor/expo-harmony/native-inputs.cmake';

type PackageManifest = {
  dependencies?: Record<string, unknown>;
  overrides?: Record<string, unknown>;
};

function resolveHar(harmonyRoot: string, value: unknown): string | null {
  if (typeof value !== 'string' || !/^\.\.?[\\/]/u.test(value)) return null;
  if (!value.toLowerCase().endsWith('.har')) return null;

  return path.resolve(harmonyRoot, value);
}

function readFileIfPresent(file: string): Buffer | null {
  try {
    return fs.readFileSync(file);
  } catch (error: unknown) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') return null;

    throw new Error(error instanceof Error ? error.message : String(error), { cause: error });
  }
}

function findArtifacts(harmonyRoot: string, manifest: PackageManifest): string[] {
  const values = [
    ...Object.values(manifest.dependencies ?? {}),
    ...Object.values(manifest.overrides ?? {}),
  ];

  return [...new Set(values.map(value => resolveHar(harmonyRoot, value)))]
    .filter((value): value is string => value !== null)
    .sort();
}

function hashFile(hash: crypto.Hash, file: string): void {
  const descriptor = fs.openSync(file, 'r');
  const buffer = new Uint8Array(1024 * 1024);

  try {
    while (true) {
      const bytesRead = fs.readSync(descriptor, buffer, 0, buffer.length, null);
      if (bytesRead === 0) break;

      hash.update(Buffer.from(buffer.subarray(0, bytesRead)).toString('binary'), 'binary');
    }
  } finally {
    fs.closeSync(descriptor);
  }
}

export function writeStamp(projectRoot: string, harmonyRoot: string): void {
  const descriptorPath = path.join(harmonyRoot, 'oh-package.json5');
  const descriptorSource = fs.readFileSync(descriptorPath);

  const manifest = JSON5.parse(descriptorSource.toString('utf8')) as PackageManifest;
  const artifactPaths = findArtifacts(harmonyRoot, manifest);

  if (artifactPaths.length === 0) {
    throw new Error('The generated Harmony project does not declare any local native HAR artifacts.');
  }

  const hash = crypto.createHash('sha256');
  hash.update('expo-harmony-native-dependencies-v1\0');
  hash.update(descriptorSource.toString('binary'), 'binary');

  const lockSource = readFileIfPresent(path.join(harmonyRoot, 'oh-package-lock.json5'));
  if (lockSource) hash.update(lockSource.toString('binary'), 'binary');

  for (const artifactPath of artifactPaths) {
    if (!fs.statSync(artifactPath).isFile()) {
      throw new Error(`Cannot fingerprint Harmony native artifact: ${artifactPath}`);
    }

    const relativePath = path.relative(projectRoot, artifactPath).split(path.sep).join('/');
    hash.update('\0artifact\0');
    hash.update(relativePath);
    hash.update('\0');
    hashFile(hash, artifactPath);
  }

  const fingerprint = hash.digest('hex');
  const stampFile = path.join(harmonyRoot, ...StampPath.split('/'));
  const source = [
    '# Generated by @expo-harmony/template. Do not edit.',
    `# Native HAR artifacts: ${artifactPaths.length}`,
    `add_compile_definitions(EXPO_HARMONY_NATIVE_INPUTS_SHA256_${fingerprint}=1)`,
    '',
  ].join('\n');
  const previous = readFileIfPresent(stampFile);

  if (previous?.toString('utf8') === source) return;

  fs.mkdirSync(path.dirname(stampFile), { recursive: true });
  const temporary = `${stampFile}.${process.pid}.${crypto.randomUUID()}.tmp`;
  try {
    fs.writeFileSync(temporary, source);
    fs.renameSync(temporary, stampFile);
  } finally {
    if (fs.existsSync(temporary)) fs.rmSync(temporary, { force: true });
  }
}
