import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { fingerprintHarmonyNativeInputsSync } from '@expo-harmony/config-plugins/internal/native-inputs';

const StampPath = '.hvigor/expo-harmony/native-inputs.cmake';

function readFileIfPresent(file: string): Buffer | null {
  try {
    return fs.readFileSync(file);
  } catch (error: unknown) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') return null;

    throw new Error(error instanceof Error ? error.message : String(error), { cause: error });
  }
}

export function writeStamp(project: string, root: string): void {
  const { artifactCount: count, fingerprint } = fingerprintHarmonyNativeInputsSync({
    lockfile: path.join(root, 'oh-package-lock.json5'),
    manifest: path.join(root, 'oh-package.json5'),
    projectRoot: project,
  });
  const file = path.join(root, ...StampPath.split('/'));
  const content = [
    '# Generated by @expo-harmony/template. Do not edit.',
    `# Native HAR artifacts: ${count}`,
    `add_compile_definitions(EXPO_HARMONY_NATIVE_INPUTS_SHA256_${fingerprint}=1)`,
    '',
  ].join('\n');

  const current = readFileIfPresent(file);
  if (current?.toString('utf8') === content) return;

  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`;

  try {
    fs.writeFileSync(temp, content);
    fs.renameSync(temp, file);
  } finally {
    if (fs.existsSync(temp)) fs.rmSync(temp, { force: true });
  }
}
