'use strict';

const fs = require('node:fs');

const { createRunOncePlugin } = require('@expo/config-plugins');
const {
  atomicWrite,
  HarmonyPaths,
  recordManagedFile,
  registerHarmonyConfigPlugin,
  withHarmonyDangerousMod,
  withModuleJson,
} = require('@expo-harmony/config-plugins');

const pkg = require('../package.json');

const EXTENSION_NAME = 'ExpoBackgroundFetchWorkSchedulerExtension';
const EXTENSION_SOURCE = './ets/expo-background-fetch/ExpoBackgroundFetchWorkSchedulerExtension.ets';
const GENERATED_MARKER = 'Automatically generated by @expo-harmony/expo-background-fetch.';
const GENERATED_SOURCE = `/**
 * ${GENERATED_MARKER}
 */

import {
  ExpoBackgroundFetchWorkSchedulerExtension as ExpoBackgroundFetchWorkSchedulerExtensionBase,
} from '@expo-harmony/expo-background-fetch';

export default class ExpoBackgroundFetchWorkSchedulerExtension
  extends ExpoBackgroundFetchWorkSchedulerExtensionBase {}
`;

function updateModuleJson(json) {
  if (json.module !== undefined && (json.module === null || typeof json.module !== 'object' || Array.isArray(json.module))) {
    throw new TypeError('Harmony module.json5 field module must be an object.');
  }
  const module = json.module || {};
  if (module.extensionAbilities !== undefined && !Array.isArray(module.extensionAbilities)) {
    throw new TypeError('Harmony module.json5 field module.extensionAbilities must be an array.');
  }
  const abilities = module.extensionAbilities || [];
  const found = abilities.filter(ability => ability?.name === EXTENSION_NAME);

  if (found.length > 1) {
    throw new TypeError(`Harmony module declares ${EXTENSION_NAME} more than once.`);
  }

  if (found.length === 1) {
    const ability = found[0];

    if (ability.type !== 'workScheduler' ||
      ability.srcEntry !== EXTENSION_SOURCE ||
      ability.exported !== false) {
      throw new TypeError(`Harmony module already declares ${EXTENSION_NAME} with incompatible settings.`);
    }

    return json;
  }

  return {
    ...json,
    module: {
      ...module,
      extensionAbilities: [
        ...abilities,
        {
          name: EXTENSION_NAME,
          srcEntry: EXTENSION_SOURCE,
          type: 'workScheduler',
          exported: false,
        },
      ],
    },
  };
}

const withBackgroundFetch = config => {
  const enabled = config.harmony?.bundleName || config.platforms?.includes('harmony');
  if (!enabled) return config;

  config = registerHarmonyConfigPlugin(config, pkg.name);
  config = withModuleJson(config, mod => {
    mod.modResults = updateModuleJson(mod.modResults);

    return mod;
  });

  return withHarmonyDangerousMod(config, async mod => {
    const moduleName = config.harmony?.moduleName || 'entry';
    const file = await HarmonyPaths.resolveHarmonyPath(
      mod.modRequest.platformProjectRoot,
      `${moduleName}/src/main/ets/expo-background-fetch/ExpoBackgroundFetchWorkSchedulerExtension.ets`
    );

    await writeGeneratedSource(file);

    recordManagedFile(mod, file, pkg.name);

    return mod;
  });
};

async function writeGeneratedSource(file) {
  let current;
  try {
    current = await fs.promises.readFile(file, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw new Error(`Unable to inspect Harmony source '${file}': ${String(error)}`);
    }
  }
  if (current !== undefined && current !== GENERATED_SOURCE && !current.includes(GENERATED_MARKER)) {
    throw new TypeError(`Harmony source '${file}' already exists and is not managed by ${pkg.name}.`);
  }
  await atomicWrite(file, GENERATED_SOURCE);
}

module.exports = createRunOncePlugin(withBackgroundFetch, pkg.name, pkg.version);
module.exports.EXTENSION_NAME = EXTENSION_NAME;
module.exports.EXTENSION_SOURCE = EXTENSION_SOURCE;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
module.exports.GENERATED_SOURCE = GENERATED_SOURCE;
module.exports.updateModuleJson = updateModuleJson;
module.exports.withBackgroundFetch = withBackgroundFetch;
module.exports.writeGeneratedSource = writeGeneratedSource;
