'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { createRunOncePlugin } = require('@expo/config-plugins');
const {
  recordManagedFile,
  registerHarmonyConfigPlugin,
  withHarmonyDangerousMod,
  withModuleJson,
} = require('@expo-harmony/config-plugins');

const pkg = require('../package.json');

const EXTENSION_NAME = 'ExpoBackgroundFetchWorkSchedulerExtension';
const EXTENSION_SOURCE = './ets/expo-background-fetch/ExpoBackgroundFetchWorkSchedulerExtension.ets';
const GENERATED_SOURCE = `/**
 * Automatically generated by @expo-harmony/expo-background-fetch.
 */

import {
  ExpoBackgroundFetchWorkSchedulerExtension as ExpoBackgroundFetchWorkSchedulerExtensionBase,
} from '@expo-harmony/expo-background-fetch';

export default class ExpoBackgroundFetchWorkSchedulerExtension
  extends ExpoBackgroundFetchWorkSchedulerExtensionBase {}
`;

function updateModuleJson(json) {
  const module = json.module && typeof json.module === 'object' && !Array.isArray(json.module)
    ? json.module
    : {};
  const abilities = Array.isArray(module.extensionAbilities)
    ? module.extensionAbilities
    : [];
  const found = abilities.filter(ability => ability?.name === EXTENSION_NAME);

  if (found.length > 1) {
    throw new TypeError(`Harmony module declares ${EXTENSION_NAME} more than once.`);
  }

  if (found.length === 1) {
    const ability = found[0];

    if (ability.type !== 'workScheduler' ||
      ability.srcEntry !== EXTENSION_SOURCE ||
      ability.exported !== false) {
      throw new TypeError(`Harmony module already declares ${EXTENSION_NAME} with incompatible settings.`);
    }

    return json;
  }

  return {
    ...json,
    module: {
      ...module,
      extensionAbilities: [
        ...abilities,
        {
          name: EXTENSION_NAME,
          srcEntry: EXTENSION_SOURCE,
          type: 'workScheduler',
          exported: false,
        },
      ],
    },
  };
}

const withBackgroundFetch = config => {
  const enabled = config.harmony?.bundleName || config.platforms?.includes('harmony');
  if (!enabled) return config;

  config = registerHarmonyConfigPlugin(config, pkg.name);
  config = withModuleJson(config, mod => {
    mod.modResults = updateModuleJson(mod.modResults);

    return mod;
  });

  return withHarmonyDangerousMod(config, async mod => {
    const file = path.join(
      mod.modRequest.platformProjectRoot,
      'entry/src/main/ets/expo-background-fetch/ExpoBackgroundFetchWorkSchedulerExtension.ets'
    );

    await fs.promises.mkdir(path.dirname(file), { recursive: true });
    await fs.promises.writeFile(file, GENERATED_SOURCE);

    recordManagedFile(mod, file, pkg.name);

    return mod;
  });
};

module.exports = createRunOncePlugin(withBackgroundFetch, pkg.name, pkg.version);
module.exports.EXTENSION_NAME = EXTENSION_NAME;
module.exports.EXTENSION_SOURCE = EXTENSION_SOURCE;
module.exports.GENERATED_SOURCE = GENERATED_SOURCE;
module.exports.updateModuleJson = updateModuleJson;
module.exports.withBackgroundFetch = withBackgroundFetch;
