'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { createRunOncePlugin } = require('@expo/config-plugins');
const {
  atomicWrite,
  HarmonyManifest,
  HarmonyPaths,
  recordManagedFile,
  registerHarmonyConfigPlugin,
  withHarmonyDangerousMod,
  withModuleJson,
} = require('@expo-harmony/config-plugins');

const pkg = require('../package.json');

const EXTENSION_NAME = 'ExpoBackgroundFetchWorkSchedulerExtension';
const EXTENSION_SOURCE = './ets/expo-background-fetch/ExpoBackgroundFetchWorkSchedulerExtension.ets';
const GENERATED_MARKER = 'Automatically generated by @expo-harmony/expo-background-fetch.';
const GENERATED_SOURCE = `/**
 * ${GENERATED_MARKER}
 */

import {
  ExpoBackgroundFetchWorkSchedulerExtension as ExpoBackgroundFetchWorkSchedulerExtensionBase,
} from '@expo-harmony/expo-background-fetch';

export default class ExpoBackgroundFetchWorkSchedulerExtension
  extends ExpoBackgroundFetchWorkSchedulerExtensionBase {}
`;

function updateModuleJson(json) {
  const result = { ...json, module: json.module === undefined ? {} : json.module };
  HarmonyManifest.getModuleOrThrow(result);

  result.module = { ...result.module };
  HarmonyManifest.ensureExtensionAbility(result, {
    name: EXTENSION_NAME,
    srcEntry: EXTENSION_SOURCE,
    type: 'workScheduler',
    exported: false,
  });

  return result;
}

const withBackgroundFetch = (config) => {
  const enabled = config.harmony?.bundleName || config.platforms?.includes('harmony');
  if (!enabled) return config;

  config = registerHarmonyConfigPlugin(config, pkg.name);
  config = withModuleJson(config, (mod) => {
    mod.modResults = updateModuleJson(mod.modResults);

    return mod;
  });

  return withHarmonyDangerousMod(config, async (mod) => {
    const file = await HarmonyPaths.resolveHarmonyPath(
      mod.modRequest.platformProjectRoot,
      path.posix.join(path.posix.dirname(HarmonyPaths.HARMONY_PATHS.moduleJson), EXTENSION_SOURCE)
    );

    await writeGeneratedSource(file);
    recordManagedFile(mod, file, pkg.name);

    return mod;
  });
};

async function writeGeneratedSource(file) {
  let current;
  try {
    current = await fs.promises.readFile(file, 'utf8');
  } catch (cause) {
    if (cause?.code !== 'ENOENT') {
      throw new Error(`Unable to inspect Harmony source '${file}': ${String(cause)}`, { cause });
    }
  }

  if (current !== undefined && current !== GENERATED_SOURCE && !current.includes(GENERATED_MARKER)) {
    throw new TypeError(`Harmony source '${file}' already exists and is not managed by ${pkg.name}.`);
  }

  await atomicWrite(file, GENERATED_SOURCE);
}

module.exports = createRunOncePlugin(withBackgroundFetch, pkg.name, pkg.version);
module.exports.EXTENSION_NAME = EXTENSION_NAME;
module.exports.EXTENSION_SOURCE = EXTENSION_SOURCE;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
module.exports.GENERATED_SOURCE = GENERATED_SOURCE;
module.exports.updateModuleJson = updateModuleJson;
module.exports.withBackgroundFetch = withBackgroundFetch;
module.exports.writeGeneratedSource = writeGeneratedSource;
